version: '3.1'
services:
  php:
    image: laravel-php:8.1
    build:
      dockerfile: ./.docker/dockerfile.php8.1.local
    entrypoint:
      - php
    command: "-v"
    working_dir: "/var/www"
    volumes:
      - .:/var/www
  
  composer:
    image: laravel-php:8.1
    build:
      dockerfile: ./.docker/dockerfile.php8.1.local
    entrypoint:
      - composer
    command: "--help"
    working_dir: "/var/www"
    volumes:
      - .:/var/www
